# Generated by Django 4.2.11 on 2024-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('publishing_date', models.DateTimeField()),
                ('thumbnail_urls', models.CharField(max_length=255)),
                ('video_count', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
    ]
