# Generated by Django 4.2.11 on 2024-03-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_count',
            new_name='view_count',
        ),
    ]
